spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema.registry.url: http://127.0.0.1:8085
        specific.avro.reader: true
#  mail:
#    host: sandbox.smtp.mailtrap.io
#    port: 2525
#    username: 5a9d8cb58ab2b4
#    password: f263829ffb03fd
server:
  port: 8083

logging:
  pattern:
    console: '%green(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1}): %msg%n%throwable'
  level:
    logging.level.org.springframework.security.web.FilterChainProxy: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: notification-service
  tracing:
    sampling:
      probability: 1.0