server:
  port: 9000

service:
  urls:
    product: http://localhost:8080
    order: http://localhost:8081
    inventory: http://localhost:8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-microservices-security-realm
  application:
    name: api-gateway

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls[0].name: Product Service
    urls[0].url: /aggregate/product-service/api-docs
    urls[1].name: Order Service
    urls[1].url: /aggregate/order-service/api-docs
    urls[2].name: Inventory Service
    urls[2].url: /aggregate/inventory-service/api-docs


# Actuator Endpoints
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Resilience4j Circuit Breaker Properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5

  # Resilience4j Timeout Properties
  timelimiter:
    configs:
      default:
        timeout-duration: 3s

  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s

logging:
  pattern:
    console: '%green(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable'
  level:
    logging.level.org.springframework.security.web.FilterChainProxy: DEBUG