spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8081

inventory:
  url: http://localhost:8082

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs


# Actuator Endpoints
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Resilience4j Circuit Breaker Properties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
              registerHealthIndicator: true
              slidingWindowType: COUNT_BASED
              slidingWindowSize: 10
              failureRateThreshold: 50
              waitDurationInOpenState: 5s
              permittedNumberOfCallsInHalfOpenState: 3
              automaticTransitionFromOpenToHalfOpenEnabled: true
              minimum-number-of-calls: 5

  # Resilience4j Timeout Properties
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s

  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 2s



logging:
  pattern:
    console: '%green(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable'
  level:
    logging.level.org.springframework.security.web.FilterChainProxy: DEBUG